### ISSUE TITLE
Unable to view the data in exported excel when the size of data is more than 500 records

### ISSUE THREAD

**Issue by sreeramyag** [wnabil/ngx-export-as#101] opened 2021-11-18 10:35 UTC
I have used ExportAs to send the data of a report, and when I am exporting the excel, I am unable to view the data in the exported report. 
The following is the attached report after exporting. 
[application.pdf](https://github.com/wnabil/ngx-export-as/files/7562060/application.pdf)

**Comment by wnabil** [comment] 2021-11-18 14:30
Please put a sample of the html structure and the used code so I can assist you. Be aware that the data have to be visible in the Dom in order to print it in the file as we are using HTML2Canvas in some types which requires the element to be visible in the view port before exporting it

**Comment by sreeramyag** [comment] 2021-11-18 14:45
I am able to see the data in the DOM.
![1](https://user-images.githubusercontent.com/75250406/142435760-93a748e5-ea12-4f70-aca1-93ec887dd98a.PNG)
when we expand a particular div, I am able to see the content in it. Please refer.
![2](https://user-images.githubusercontent.com/75250406/142436351-aaa05e21-f6fc-41f4-bf16-5b306f801728.PNG)
when i apply filter and then perform the excel export functionality, I am able to see the filtered data too, only when i am not applying any filter and anything, I am unable to see the data.

this is the block of code used in component.ts, 

  this.exportAsService.get({
                type: 'pdf',
                elementIdOrContent: 'individual-content',
                options: {
                    jsPDF: {
                        orientation: 'portrait'
                    }
                }
            }).subscribe((base64Data: any) => {
                this.appService.sendMail(base64Data);
            });

I have imported the ExportAsService from ngx-export-as.

**Comment by wnabil** [comment] 2021-11-18 17:02
Is the data or any container hidden in any css way like display none, opacity 0, font color equals the background color etc... ?

**Comment by sreeramyag** [comment] 2021-11-19 04:49
No

**Comment by wnabil** [comment] 2021-11-22 01:48
Please create a demo project and share it with me as I tested it and can't reproduce

**Comment by sreeramyag** [comment] 2021-11-22 12:23
the attached pdf is the output, when we perform export as pdf.
[myFile (7).pdf](https://github.com/wnabil/ngx-export-as/files/7580878/myFile.7.pdf)
to reproduce the issue,
git clone https://github.com/wnabil/ngx-export-as.git
replace app.component.html with - 
[app.component.zip](https://github.com/wnabil/ngx-export-as/files/7580903/app.component.zip)

**Comment by wnabil** [comment] 2021-11-24 00:45
So first of all here is a file with 2975 rows in it.
[myFile.pdf](https://github.com/wnabil/ngx-export-as/files/7591776/myFile.pdf)

I noticed more than that the generated pdf appears with blank pages yes so matching this with your project rows "500" this looks like a rendering issue with html2pdf.js library and it seems more about the pages "max handled pages as I tested is 59" OR maybe depends on the device specifications like CPU/RAM "faster generates more until a timeout happens in the library and the process cancelled"

However I have searched a bit for this issue in the lib repo and found this issue
https://github.com/eKoopmans/html2pdf.js/issues/19#issuecomment-361625732

You can test the solutions they provided in the comments or I suggest you to split your generated pdf into smaller chunk of files or for huge data export use a server side pdf generator as actually this file took around 15 seconds to be generated in my system "Really decent desktop" which is extremely too much specially for other devices like mobile phones or laptops - depends on your project

Closing this issue as it is from outside of the project scope and thanks for the info

**Closed by wnabil** 2021-11-24 00:45 UTC
